config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # 会員側ルーティング
  root to: "public/homes#top"

  scope module: :public do
    get "/about", to: "homes#about"
    get "users/information/edit", to: "users#edit"
    patch "users/information", to: "users#update"
    get "users/:id/confirmation", to: "users#confirm", as: "confirm_user"
    patch "users/:id/withdraw", to: "users#withdraw", as: "user_withdraw"
    get "/privacy_policy", to: "homes#privacy_policy"
    get "/terms", to: "homes#terms"

    resources :posts do
      resources :post_comments, only: [:create, :destroy], path: "comments" # URLをpost_commentsからcommentsに変更する
      resource :like, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "following" => "relationships#following", as: "following"
      get "followers" => "relationships#followers", as: "followers"
      member do
        get :likes
      end
    end

    get "search", to: "searches#search"
    resources :searches, only: [:index]
    resources :categories, only: [:show, :index]

    resources :notifications, only: [:update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :withdaw # memberをつけると:idが付与される
      end
    end

    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :show, :destroy]
    resources :categories
    get "search", to: "searches#search"
    resources :searches, only: [:index]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @categories = Category.all
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: "カテゴリを登録しました"
    else
      redirect_to admin_categories_path, alert: "カテゴリの作成に失敗しました"
    end
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: "カテゴリを更新しました"
    else
      redirect_to edit_admin_category_path, alert: "カテゴリの更新に失敗しました"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path, notice: "カテゴリを削除しました"
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 offset-3">
      <h4 class="my-4 ml-4">カテゴリ編集</h4> 
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with model: @category, url: admin_category_path(@category), local: true do |f| %>
        <div class="form-group d-flex align-items-center">
          <%= f.text_field :name, class: "form-control mr-3", placeholder: "カテゴリ名", style: "width: 200px;" %>
          <%= f.submit "保存", class: "btn btn-secondary" %>
          <%= link_to "削除", admin_category_path(@category), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger ml-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
  <h4 class="my-4 text-center">カテゴリ一覧・追加</h4>

  <div class="row m-4">
    <div class="col d-flex justify-content-center">
      <%= form_with(model: @category, local: true, url: admin_categories_path, class: "form-inline") do |f| %>

        <div class="mt-1">
          <%= f.text_field :name, placeholder: "カテゴリ名", class: "form-control" %>
          <%= f.submit "登録する", class: "btn btn-secondary ml-3" %>
        </div>

      <% end %>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-md-4">
      <table class="table table-bordered">

        <thead class="thead-light">
          <tr>
            <th>カテゴリ</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td class="text-center"><%= link_to '編集する', edit_admin_category_path(category), class: "btn btn-secondary btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>

      </table>
    </div>
  </div>
</div>