config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # 会員側ルーティング
  root to: "public/homes#top"

  scope module: :public do
    get "/about", to: "homes#about"
    get "users/information/edit", to: "users#edit"
    patch "users/information", to: "users#update"
    get "users/:id/confirmation", to: "users#confirm", as: "confirm_user"
    patch "users/:id/withdraw", to: "users#withdraw", as: "user_withdraw"
    get "/privacy_policy", to: "homes#privacy_policy"
    get "/terms", to: "homes#terms"

    resources :posts do
      resources :post_comments, only: [:create, :destroy], path: "comments" # URLをpost_commentsからcommentsに変更する
      resource :like, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "following" => "relationships#following", as: "following"
      get "followers" => "relationships#followers", as: "followers"
      member do
        get :likes
      end
    end

    get "search", to: "searches#search"
    resources :searches, only: [:index]
    resources :categories, only: [:show, :index]

    resources :notifications, only: [:update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :withdaw # memberをつけると:idが付与される
      end
    end

    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :show, :destroy]
    resources :categories
    get "search", to: "searches#search"
    resources :searches, only: [:index]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :notifications, dependent: :destroy

  # フォローされている関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォロワーの取得
  has_many :followers, through: :passive_relationships, source: :follower
  # フォローしている関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  #  フォローしている人の取得
  has_many :following, through: :active_relationships, source: :followed

  validates :name, presence: true, length: { in: 1..7 }
  validates :introduction, length: { maximum: 50 }

  has_one_attached :image

  def get_image
    image.attached? ? image : "no_image.jpg"
  end

  # フォローする
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  # 　フォローを解除する
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  # フォローしているかの確認
  def following?(user)
    following.include?(user)
  end

  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      # 完全一致
      where("name LIKE ?", word).where(is_active: true)
    elsif search == "partial_match"
      # 部分一致
      where("name LIKE ?", "%#{word}%").where(is_active: true)
    else
      # デフォルトは部分一致
      where("name LIKE ?", "%#{word}%").where(is_active: true)
    end
  end

  # 通知を作成するメソッド
  def create_notification(action, notifiable)
    notifications.create(
      user_id: self.id,
      action: action,
      notifiable: notifiable,
      read: false
    )
  end

  # ゲストユーザー機能
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
      user.introduction = "ゲストユーザーです"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_update :deactivate_user, if: :deactivating?

  private
    # is_activeがfalseになる場合に呼ばれるメソッド
    # ステータスを退会済みにするだけでは関連データが削除されない為に必要
    def deactivate_user
      posts.destroy_all
      post_comments.destroy_all
      likes.destroy_all
      passive_relationships.destroy_all
      active_relationships.destroy_all
    end

    # is_activeがfalseに変更されたかどうかをチェックするメソッド
    # ステータスが退会済みであるかどうかを
    def deactivating?
      is_active_changed? && !is_active
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_root_path(@user), notice: "会員情報が更新されました"
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :edit
    end
  end

  def withdraw
    @user.update(is_active: false)
    redirect_to admin_root_path
  end

  def user_params
    params.require(:user).permit(:name, :email, :is_active)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーでログインしました。"
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">

  <div class="row d-flex justify-content-center">
    <div class="col-4 mt-5 mb-3">
      <h4><%= @user.name %>さんの会員情報編集</h4>
    </div>
  </div>

  <div class="row d-flex justify-content-center mt-2">
    <div class="col-4">
      <%= form_with model: @user, url: admin_user_path(@user), local: true, method: :patch do |f| %>

        <div>

          <div class="mb-3">
            会員ID &ensp; <%= @user.id %>
          </div>

          <div>
            <%= f.label :name, "ニックネーム" %>
          </div>
          <div>
            <%= f.text_field :name, class: "form-control" %>
          </div>

          <div class="mt-3">
            <%= f.label :email, "メールアドレス" %>
          </div>
          <div>
            <%= f.text_field :email, class: "form-control" %>
          </div>

          <div class="mt-3">
            <%= f.label :is_active, "会員ステータス", class: "pb-2" %>
            <!--ユーザーの会員ステータスをラジオボタンで選択-->
            <div class="d-flex">
              <div>
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active_true, "有効", class: "pl-1" %>
              </div>
              <div class="ml-4">
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active_false, "退会", class: "pl-1"  %>
              </div>
            </div>
          </div>

          <div class="mt-2 d-flex">
            <%= f.submit "保存", class:"btn btn-secondary" %>
            <%= link_to "戻る", admin_root_path, class: "btn btn-secondary ml-auto" %>
          </div>

        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>