config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # 会員側ルーティング
  root to: "public/homes#top"

  scope module: :public do
    get "/about", to: "homes#about"
    get "users/information/edit", to: "users#edit"
    patch "users/information", to: "users#update"
    get "users/:id/confirmation", to: "users#confirm", as: "confirm_user"
    patch "users/:id/withdraw", to: "users#withdraw", as: "user_withdraw"
    get "/privacy_policy", to: "homes#privacy_policy"
    get "/terms", to: "homes#terms"

    resources :posts do
      resources :post_comments, only: [:create, :destroy], path: "comments" # URLをpost_commentsからcommentsに変更する
      resource :like, only: [:index, :create, :destroy]
    end

    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "following" => "relationships#following", as: "following"
      get "followers" => "relationships#followers", as: "followers"
      member do
        get :likes
      end
    end

    get "search", to: "searches#search"
    resources :searches, only: [:index]
    resources :categories, only: [:show, :index]

    resources :notifications, only: [:update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
  end

  # 管理者側ルーティング
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :withdaw # memberをつけると:idが付与される
      end
    end

    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only: [:index, :show, :destroy]
    resources :categories
    get "search", to: "searches#search"
    resources :searches, only: [:index]
  end
end

app/views/layouts/_categories.html.erb
<div class="mt-5 px-0">

  <div class="pb-5 text-center border-bottom">
    <strong>カテゴリ一覧</strong>
  </div>

  <% @categories.each do |category| %>
    <div class="py-3 pl-4 border-bottom">
      ・<%= link_to category.name, posts_path(category_id: category.id) %>
    </div>
  <% end %>

</div>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg" style="background-color: #000; padding: 40px 0;">
    <div class="container">

      <a class="navbar-brand py-0 text-white" href="/">
        GamersGear
      </a>

      <div class="ml-auto">
        <div class="links">
          <ul class="navbar-nav">
            
            <li class="nav-item">
              <a href="/about" class="nav-link text-white mr-2">このサイトについて</a>
            </li>
            
            <li class="nav-item">
              <a href="/terms" class="nav-link text-white mr-2">利用規約</a>
            </li>
            
            <li class="nav-item">
              <a href="/privacy_policy" class="nav-link text-white">プライバシーポリシー</a>
            </li>
            
          </ul>
        </div>
      </div>

    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color: #000; padding: 15px 0;">
    <div class="container">
      
      <a class="navbar-brand py-0 text-white" href="/">
        <%= image_tag 'GamersGear.png', alt: 'GamersGear', size: "45x45" %>GamersGear
      </a>
      
      <div class="mx-auto">
        <%= render 'layouts/search' %>
      </div>
      
      <div class="ml-auto">
        <div class="links">

          <ul class="navbar-nav">

            <% if user_signed_in? %>
            <!--ユーザーでログインしている時-->
              <li class="nav-item">
                <%= render 'layouts/notification' %>
              </li>
            
              <li class="nav-item ml-1">
                <%= link_to user_path(current_user), class: 'nav-link text-white' do %>
                  マイページへ
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_post_path, class: 'nav-link text-white' do %>
                  投稿する
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_user_session_path, class: 'nav-link text-white', method: :delete do %>
                  ログアウト
                <% end %>
              </li>

            <% elsif admin_signed_in? %>
            <!--管理者でログインしている時-->
              <li class="nav-item">
                <%= link_to admin_root_path, class: 'nav-link text-white' do %>
                  会員一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to admin_posts_path, class: 'nav-link text-white' do %>
                  投稿一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to admin_categories_path, class: 'nav-link text-white' do %>
                  カテゴリ一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_admin_session_path, class: 'nav-link text-white', method: :delete do %>
                  ログアウト
                <% end %>
              </li>

            <% else %>
            <!--ログインしていない時-->
              <li class="nav-item">
                <%= link_to about_path, class: 'nav-link text-white' do %>
                  このサイトについて
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
                  新規会員登録
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
                  ログインする
                <% end %>
              </li>

            <% end %>
          </ul>
        </div>

      </div>
    </div>
  </nav>
</header>

app/views/layouts/_notification.html.erb
<li class="dropdown">
  <button class="btn btn-black position-relative" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fa-regular fa-bell fa-lg"></i>
    <% unread_count = current_user.notifications.where(read: false).count %>
    <% if unread_count > 0 %>
      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
        <%= unread_count %>
      </span>
    <% end %>
  </button>
  
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
    <% if current_user.notifications.where(read: false).any? %>
      <small class="dropdown-item disabled">直近10件の未読の通知を表示しています</small>
      <% current_user.notifications.where(read: false).limit(10).order(created_at: :desc).each do |notification| %>
        <%= link_to notification_message(notification), public_notification_path(notification), method: :patch, class: "dropdown-item" %>
      <% end %>
      <%= link_to 'すべての通知を削除', destroy_all_public_notifications_path, method: :delete, remote: true, class: "dropdown-item text-danger" %>
    <% else %>
      <span class="dropdown-item disabled">通知はありません</span>
    <% end %>
  </div>
</li>

app/views/layouts/_search.html.erb
<!--検索機能-->
<div class="ml-5 search-form">
  <%= form_with url: (admin_signed_in? ? admin_search_path : search_path), local: true, method: :get, class: 'form-inline' do |f| %>
    <%= f.select :range, options_for_select([['ユーザー', 'User'], ['レビュー', 'Post'], (admin_signed_in? ? ['コメント', 'PostComment'] : nil)].compact), class: 'form-control　searchform' %>
    <%= f.text_field :word, placeholder: "キーワードを入力", class: 'form-control searchform' %>
    <%= f.button :submit, class: 'btn btn-info form-control searchform' do %>
      <i class="fa fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamersgear</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/21474bdd09.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column min-vh-100" style="background-color: #f0f8ff">
    <%= render 'layouts/header' %>
      <main class="flex-grow-1">

        <% if flash[:notice] %>
          <div class="alert alert-success text-center m-0"><%= flash[:notice] %></div>
        <% elsif flash[:alert] %>
          <div class="alert alert-danger text-center "><%= flash[:alert] %></div>
        <% end %>

        <%= yield %>

      </main>
    <%= render 'layouts/footer' %>
  </body>
</html>